import { createAvatar } from "@dicebear/core";
import { bottts } from "@dicebear/collection";

/**
 * A deterministic robot drawn for a wallet that has not published one.
 *
 * # Why this is generated here and never fetched
 *
 * DiceBear runs a hosted API at `api.dicebear.com`, and using it would mean
 * the browser requesting one URL per avatar with the wallet address in the
 * query string. That hands a third party a live feed of which wallets each
 * visitor is looking at: an order book page would leak the entire visible set
 * in one burst, and a trade room leaks exactly who the viewer is dealing
 * with, at the moment they are dealing with them. In a P2P fiat market that
 * is the same class of exposure `lib/counterparties.ts` refuses to expose
 * through the protocol itself, and it would be strange to close that door and
 * then leave this one open.
 *
 * It would also make every avatar in the interface depend on somebody else's
 * uptime, and put a third-party origin in the critical path of a page whose
 * whole point is that it depends on no single company.
 *
 * `@dicebear/core` and `@dicebear/collection` are the same generator as an
 * npm package, rendering to SVG in process. Output is a pure function of the
 * seed and options, so the robot is identical on every device with no request
 * at all — which is a stronger guarantee than the hosted API gives, since a
 * hosted response can change when they deploy.
 *
 * # SVG here, and no relaxation of the upload allowlist
 *
 * `openfiat_content::MediaType` deliberately excludes SVG, because an SVG is
 * a scriptable document and accepting one from a stranger is accepting their
 * script. That exclusion is about uploaded content and it stays exactly as it
 * is. This markup is generated by our own code from a seed we chose, on the
 * device rendering it, and never leaves — it is not user-supplied, so it is
 * not the thing that rule guards against. Nothing here is an argument for
 * letting an uploaded SVG through.
 *
 * # It has to look like a placeholder
 *
 * A merchant who has published nothing must not appear to have picked a robot
 * as their logo. The generator is only half of that; see
 * `components/wallet-avatar.tsx`, which renders these muted and inside a
 * dashed ring so the difference between "chose this picture" and "has not
 * chosen one" is visible at a glance.
 */

/**
 * The brand palette, sampled from `app/globals.css`.
 *
 * These are duplicated from CSS rather than read from it, because the avatar
 * is generated during server rendering where there is no document to read
 * custom properties from, and reading them on the client only would produce
 * a different SVG before and after hydration.
 *
 * `tests/placeholder-avatar.test.ts` parses `app/globals.css` and fails if
 * these three stop matching it, so the duplication cannot silently drift —
 * globals.css remains the source of truth and this is a checked copy of it.
 *
 * DiceBear wants hex without the leading `#`.
 */
export const BRAND_HEX = {
  brand: "0070f8",
  brandHover: "2b8fff",
  brandTeal: "00b098",
} as const;

/**
 * `hex` mixed towards white by `amount`, as another bare hex.
 *
 * A derivation rather than a fourth constant, so `app/globals.css` stays the
 * only place a brand colour is *chosen*. Picking a lighter blue by hand would
 * have put a value in this file that the drift test cannot check against
 * anything, and it would stop tracking the brand the first time the palette
 * moves. This tracks it: change `--color-brand-hover` and the chassis moves
 * with it, still lighter by the same step.
 */
function lighten(hex: string, amount: number): string {
  const channel = (offset: number) => {
    const value = Number.parseInt(hex.slice(offset, offset + 2), 16);
    return Math.round(value + (0xff - value) * amount)
      .toString(16)
      .padStart(2, "0");
  };
  return `${channel(0)}${channel(2)}${channel(4)}`;
}

/**
 * The robot's chassis: `--color-brand-hover`, lightened.
 *
 * The chassis used to be `--color-brand-hover` itself, painted straight onto
 * a background whose first gradient stop is `--color-brand`. Those two are
 * adjacent blues — 1.25:1 against each other once the placeholder's dimming
 * was composited in — so the robot's silhouette had almost nothing to
 * separate it from its own backdrop, and at the 32px a table row gives it
 * there was nothing left to see. That was the real reason these read as
 * invisible: not that the avatar was too dark against the page, but that the
 * robot was the same colour as the disc it was drawn on.
 *
 * 0.55 towards white takes that to 2.5:1, which is enough for the shape to
 * survive being 32px wide, while the hue is still unmistakably the brand's.
 */
export const CHASSIS_HEX = lighten(BRAND_HEX.brandHover, 0.55);

/**
 * Fixed options for every placeholder.
 *
 * The background runs the logo's blue-to-teal gradient, and the robot's own
 * chassis takes a lightened brand blue so it reads against it. Restricting
 * the palette this hard is the point: DiceBear's default bottts palette is a
 * bright multicoloured set that would make each placeholder look like a
 * deliberate, individual choice. Constrained to the brand's own colours, the
 * variation between wallets is in the robot's shape rather than its colour,
 * which is recognisable without looking chosen.
 */
const OPTIONS = {
  backgroundColor: [BRAND_HEX.brand, BRAND_HEX.brandTeal],
  backgroundType: ["gradientLinear" as const],
  baseColor: [CHASSIS_HEX],
};

/**
 * Rendering is not cheap and lists re-render often, so each seed is drawn
 * once per page load.
 *
 * Unbounded on purpose: the key set is the wallets a person actually scrolls
 * past in one session, which is small, and it is discarded on navigation
 * anyway. A bounded cache here would evict exactly the avatars still on
 * screen during a long scroll.
 */
const cache = new Map<string, string>();

/**
 * The placeholder for `seed`, as a data URI ready for an `<img src>`.
 *
 * `seed` must be a canonical identity — a base58 wallet address, or a peer id
 * in one consistent encoding. It is what makes the robot stable, so passing a
 * shortened or differently-cased form of the same identity in two places
 * would draw two different robots for one wallet.
 */
export function placeholderAvatarUri(seed: string): string {
  const cached = cache.get(seed);
  if (cached) return cached;
  const uri = createAvatar(bottts, { seed, ...OPTIONS }).toDataUri();
  cache.set(seed, uri);
  return uri;
}
